# Site settings
exclude: [vendor]

title: KR Dvorak
job_title1: Software Developer
job_title2: Traveler    
current_location: Philippines    
email: wiiGenocide@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://http://kreighza.github.io" # the base hostname & protocol for your site

github: https://github.com/breisamoralde?tab=activity
gitlab: https://gitlab.com/u/zeitgeist
linkedin: https://ph.linkedin.com/pub/breisa-moralde/35/7b1/2a1
google_maps_broswer_key: AIzaSyDHNeP7Tfl6Y-d-h7oXJlSxLyCc8rGkjTY

travelBook_title: Hey There!
travelBook_intro: If you are reading this, then welcome to my itenerary! I am an avid traveler! Traveling has been one of my only vices in life. I have been to a lot of places and I am keen to see and experience more! This page documents the places I have been to, the places where I want to go and the little adventures and mishaps that went along with it! :)

travelBook_trivia:
- answer: 0
  question: Total countries visited
  id: trivia1
- answer: eat
  question: Must do when traveling
  id: trivia2
- answer: SG
  question: Next Destination
  id: trivia3
  
travelBook_photos1:
- place: Chinatown, Singapore
  image: ../images/travelBook/photos/photo1.jpg
- place: Merlion
  image: ../images/travelBook/photos/photo2.jpg
- place: Chicken Rice, yum!
  image: ../images/travelBook/photos/photo3.jpg
  
travelBook_photos2:
- place: Legoland, Johor Bahru Malaysia
  image: ../images/travelBook/photos/photo4.jpg
- place: Replica of the Forbidden City in Legoland
  image: ../images/travelBook/photos/photo5.jpg
- place: Replica of Taj Mahal in Legoland
  image: ../images/travelBook/photos/photo6.jpg
- place: Replica of Singapore in Legoland
  image: ../images/travelBook/photos/photo7.jpg

travelBook_photos3:
- place: Replica of Thai Temple in Legoland
  image: ../images/travelBook/photos/photo8.jpg
- place: A Series of Buddha Statues in Thailand
  image: ../images/travelBook/photos/photo9.jpg
- place: A lotus flower in Thailand
  image: ../images/travelBook/photos/photo10.jpg
  
navigation:
- text: home
  url: /index.html
- text: travel stuff
  url: /itenerary/
- text: blog
  url: /blog.html
- text: contact
  url: /contact.html
  
skill_set_list:
- text: MeteorJS
  source: https://www.meteor.com/
  color: DE4F4F
  img: images/skills/meteor.png
- text: Firebase
  source: https://www.firebase.com/
  color: ECE970
  img: images/skills/firebase.png
- text: AngularJS
  source: https://angularjs.org/
  color: DE5C4F
  img: images/skills/angularJS.png
- text: HTML5
  source: http://www.w3schools.com/html/html5_intro.asp
  color: DE7E4F
  img: images/skills/html5.png
- text: Grails
  source: http://www.grails.org
  color: 86DE4F
  img: images/skills/grails.jpg
- text: Jekyll
  source: http://jekyllrb.com/
  color: 9D9898
  img: images/skills/jekyll.png
- text: CSS3
  source: http://www.w3schools.com/css/css3_intro.asp
  color: 4FCEDE
  img: images/skills/css3.png
- text: Git
  source: https://git-scm.com/
  color: 443C35
  img: images/skills/git.png
  
photo_credits:
- author: Luis Llerena
  source: https://unsplash.com/negativespace
- author: Vadim Sherbakov
  source: https://unsplash.com/madebyvadim

experience_title: EXPERIENCE
experience_prefix: Kreisa has been a Software Developer for 
skillSet_title: SKILL SET
skillSet_info: Some of the frameworks Kreisa has used in her projects.
project_title: PROJECTS
project_info: Stuff Kreisa has been up to.

jobStart: December 1, 2011

# List work experience here.
# First in line would be the latest.
workExperience:
- jobTitle: Software Developer
  durationStart: Jan. 1, 2013
  durationEnd: Present
  location: Cebu, Philippines
  company: Synacy
  companyUrl: http://synacy.com/
  companyLogo: images/synacy.png 
  jobDescription: Synacy is a technology company. Interests within the wider group are diverse, ranging from mineral exploration headquartered in Canada to information technology and telecommunications businesses in Singapore and Australia. The senior management is Australian and Cebu based.Our software development projects provide interesting technical challenges including scaling a high volume transactional system, optimising and building APIs for our partners and developing exciting front end products. We also have a few new ideas that will keep things interesting. We employ agile development methods utilising Java, Grails, Spring, PostgreSQL and LAMP.
- jobTitle: Software Developer
  durationStart: Dec. 1, 2011
  durationEnd: May 30, 2016
  location: Makati, Philippines
  company: Orange and Bronze
  companyUrl: http://orangeandbronze.com/
  companyLogo: images/onb.jpg
  jobDescription: The role of the software developer is the creation of software. The tasks involved include but are not limited to the following programming, installation and configuration of software, design of software research, testing, collaboration with teammates and other stakeholders, and documentation. The software developer may also assume the role of consultant. The role largely involves assisting or advising clients in the field of software development. Other roles and tasks may be assigned as needed.

graduatedText: Graduated from college
graduatedDate: Nov. 2011

projects:
- title: Uikit Complete Package for Meteor
  images: 
    - images/projects/uikitcomplete/uikitcomplete2.png
    - images/projects/uikitcomplete/uikitcomplete1.png
  techUsed: 
    - git
    - meteor
  link: https://atmospherejs.com/coffeejesus/uikit-complete
  description: Uikit Complete is a meteor package I personally created so that I could easily integrate UIkit into my meteor projects. At that time, I could not find an updated and complete version, so I made one myself. It is constantly updated and maintained with the latest version of Uikit. 
- title: AzazelRO
  images: 
    - images/projects/azazel/azazel1.png
    - images/projects/azazel/azazel2.png
    - images/projects/azazel/azazel3.png
    - images/projects/azazel/azazel4.png
  techUsed: 
    - grails 2.4.4
    - html
    - css
    - mysql
    - php5
    - nginx
    - hercules
  link: http://azazelro.com
  description: AzazelRO is an attempt at creating our very own private server for the classic game "Ragnarok Online". Most of my responsibilities include server setup (using Ubuntu in Digital Ocean), making the website where people can register for the game, and setting up robrowser for it the game to be playable on the browser too. Development has been discontinued.

jekyll_timeago:
  today: 'today'
  yesterday: 'yesterday'
  tomorrow: 'tomorrow'
  and: 'and'
  suffix: ''
  prefix: ''
  suffix_future: 'in'
  prefix_future: ''
  years: 'years'
  year: 'year'
  months: 'months'
  month: 'month'
  weeks: 'weeks'
  week: 'week'
  days: 'days'
  day: 'day'
  
# Build settings
markdown: kramdown
