# Site settings
title: Kreisa Moralde
job_title1: Software Developer
job_title2: Traveler    
current_location: Philippines    
email: wiiGenocide@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://http://kreighza.github.io" # the base hostname & protocol for your site

github: https://github.com/breisamoralde
gitlab: https://gitlab.com/u/zeitgeist
linkedin: https://ph.linkedin.com/pub/breisa-moralde/35/7b1/2a1


# Build settings
markdown: kramdown
