# Site settings
title: Kreisa Moralde
job_title1: Software Developer
job_title2: Traveler    
current_location: Philippines    
email: wiiGenocide@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://http://kreighza.github.io" # the base hostname & protocol for your site

github: https://github.com/breisamoralde
gitlab: https://gitlab.com/u/zeitgeist
linkedin: https://ph.linkedin.com/pub/breisa-moralde/35/7b1/2a1

navigation:
- text: home
  url: /index.html
- text: blog
  url: /blog.html
- text: contact
  url: /contact.html
  
skillSet_info: I have used a variety of frameworks in a lot of my projects.

# List work experience here.
# First in line would be the latest.
workExperience:
- jobTitle: Software Developer
  durationStart: January 1, 2013
  durationEnd: Present
  location: Cebu, Philippines
  company: Synacy
  companyUrl: http://synacy.com/
  companyLogo: images/synacy.png 
  jobDescription: Synacy is a technology company. Interests within the wider group are diverse, ranging from mineral exploration headquartered in Canada to information technology and telecommunications businesses in Singapore and Australia. The senior management is Australian and Cebu based.Our software development projects provide interesting technical challenges including scaling a high volume transactional system, optimising and building APIs for our partners and developing exciting front end products. We also have a few new ideas that will keep things interesting. We employ agile development methods utilising Java, Grails, Spring, PostgreSQL and LAMP.
- jobTitle: Software Developer
  durationStart: December 1, 2011
  durationEnd: Present
  location: Makati, Philippines
  company: Orange and Bronze
  companyUrl: http://orangeandbronze.com/
  companyLogo: images/onb.jpg
  jobDescription: The role of the software developer is the creation of software. The tasks involved include but are not limited to the following programming, installation and configuration of software, design of software research, testing, collaboration with teammates and other stakeholders, and documentation. The software developer may also assume the role of consultant. The role largely involves assisting or advising clients in the field of software development. Other roles and tasks may be assigned as needed.
  

graduatedText: Graduated from college
graduatedDate: November 2011

jekyll_timeago:
  today: 'today'
  yesterday: 'yesterday'
  tomorrow: 'tomorrow'
  and: 'and'
  suffix: ''
  prefix: ''
  suffix_future: 'in'
  prefix_future: ''
  years: 'years'
  year: 'year'
  months: 'months'
  month: 'month'
  weeks: 'weeks'
  week: 'week'
  days: 'days'
  day: 'day'
  
# Build settings
markdown: kramdown
